version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8083:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - dind

  dind:
    image: docker:24-dind   # cliente + daemon de docker
    container_name: dind
    privileged: true
    volumes:
      - dind-storage:/var/lib/docker

volumes:
  jenkins_home:
  dind-storage:
