version: '3.9'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8083:8080"   # Jenkins UI
      - "50000:50000" # Jenkins agents
    environment:
      - DOCKER_HOST=tcp://dind:2375
    volumes:
      - ./jenkins_home:/var/jenkins_home

  dind:
    image: docker:24-dind
    container_name: dind
    privileged: true
    environment:
    - DOCKER_TLS_CERTDIR=
    ports:
      - "8082:8082"   # exponemos el puerto del contenedor web
      - "2375:2375"
    volumes:
      - dind-storage:/var/lib/docker

volumes:
  jenkins_home:
  dind-storage:
