version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8083:8080"   # Jenkins UI
      - "50000:50000" # Jenkins agents
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_HOST: tcp://dind:2375

  dind:
    image: docker:24-dind
    container_name: dind
    privileged: true
    ports:
      - "2375:2375"
      - "8082:8082" 
    volumes:
      - dind-storage:/var/lib/docker

volumes:
  jenkins_home:
  dind-storage:
